module.exports = Object.freeze({

    AGENDAMENTO_CRIADO: 'AGENDAMENTO_CRIADO',
    AGENDAMENTO_CANCELADO: 'AGENDAMENTO_CANCELADO',
    AGENDAMENTO_REAGENDADO: 'AGENDAMENTO_REAGENDADO',

    AGENDAMENTO_ENCONTRADO: 'AGENDAMENTO_ENCONTRADO',
    AGENDAMENTO_NAO_ENCONTRADO: 'AGENDAMENTO_NAO_ENCONTRADO',

    HORARIO_VALIDO: 'HORARIO_VALIDO',
    HORARIO_OCUPADO: 'HORARIO_OCUPADO',
    HORARIOS_ENCONTRADOS: 'HORARIOS_ENCONTRADOS',
    SEM_HORARIOS_LIVRES: 'SEM_HORARIOS_LIVRES',

    FORA_DO_HORARIO: 'FORA_DO_HORARIO',

    MULTIPLOS_CLIENTES: 'MULTIPLOS_CLIENTES',

    ACAO_INVALIDA: 'ACAO_INVALIDA',

    ERRO: 'ERRO'

});