const STATUS = {
    HORARIO_LIVRE: 'HORARIO_LIVRE',
    HORARIO_OCUPADO: 'HORARIO_OCUPADO',
    AGENDAMENTO_CRIADO: 'AGENDAMENTO_CRIADO',
    CLIENTE_NAO_ENCONTRADO: 'CLIENTE_NAO_ENCONTRADO',
    SERVICO_NAO_ENCONTRADO: 'SERVICO_NAO_ENCONTRADO',
    ERRO: 'ERRO'
};

module.exports = STATUS;